### ISSUE TITLE
Open laz file in read and write mode failed

### ISSUE THREAD

**Issue by arthur-leguennec** [laspy/laspy#73]
Hello everyone,

I'm trying to open a laz file to read and write on the classification. But when I run this command:
`inFile = File("test.laz", mode = "rw")`
I have the following message:

    File "D:\Program Files (x86)\Python36-64\lib\site-packages\laspy\file.py", line 64, in __init__
    self.open()
    File "D:\Program Files (x86)\Python36-64\lib\site-packages\laspy\file.py", line 94, in open
    self._writer = base.Writer(self.filename,mode = self._mode)
    File "D:\Program Files (x86)\Python36-64\lib\site-packages\laspy\base.py", line 268, in __init__
    self.setup_read_write(vlrs, evlrs, read_only=False)
    File "D:\Program Files (x86)\Python36-64\lib\site-packages\laspy\base.py", line 293, in setup_read_write
    self.data_provider.map()
    File "D:\Program Files (x86)\Python36-64\lib\site-packages\laspy\base.py", line 209, in map
    raise laspy.util.LaspyException("Error mapping file: " + str(e))
    laspy.util.LaspyException: Error mapping file: 'bool' object has no attribute 'fileno'

If someone knows why I have this, I'll happy to know the answer!
I work on windows 10 64 bits, Python 3.6.2 and laspy 1.5.0

Thanks,
Arthur

**Comment by arthur-leguennec** [comment]
Just a precision (i remarked this just now ...), it works with a las file

**Comment by grantbrown** [comment]
Hmm, does it work on the las file which is equivalent to the laz file you're working with? That is, if you extract the laz file using lazip, does laspy read the result correctly?

**Comment by arthur-leguennec** [comment]
Yes, it's works with the same point cloud if it's a las but not a laz. And it's doesn't change if I extract a las file with laszip

**Comment by grantbrown** [comment]
Can you replicate the error with version 1.5.1 from GitHub? (I just incremented the version because we got behind on that. There are some changes which haven't been deployed to the package index).

**Comment by zwnk** [comment]
i get the same when opening a laz file in rw mode.
laspy 1.5.1 is installed.

**Comment by niranjanreddy891** [comment]
got it

**Comment by grantbrown** [comment]
Laspy doesn't support rw for laz files, but should probably give a better error. Laz files are currently read-only.

**Comment by zwnk** [comment]
good to know :)

**Comment by Sajjadmanal** [comment]
@grantbrown @arthur-leguennec How can I read .laz file using laspy? I am getting below error:
`LaspyException: Error mapping file: Laszip was not found on the system`

**Comment by niranjanreddy891** [comment]
@Sajjadmanal have you tried [this](https://stackoverflow.com/questions/49500149/laspy-cannot-find-laszip-when-is-installed-from-source-laszip-is-in-path)

**Comment by niranjanreddy891** [comment]
Error says Laszip is missing. Please install laszip

**Comment by Sajjadmanal** [comment]
@niranjanreddy891  I installed laszip using :
`conda install -c conda-forge laszip`

I checked it is installed successfully using: `conda list` 
Ran again but I gives me the same error.

**Comment by DineshChandra94** [comment]
@Sajjadmanal 
download laszip-cli.exe from [here](http://lastools.org/download/laszip-cli.exe) and add its path to the environment. This should solve your issue.
If the above link is not working than you can go to https://laszip.org and then brows down to Binaries;  here you should see laszip-cli.exe, download it.

**Comment by tmontaigu** [comment]
Closing as laspy 2.0 support writting LAZ files (However this is not done by opening in `rw` mode since `laspy.File` does not exists anymore)
